= OWASP Dependency Check (ODC) in SWAMP
:toc: left
Vamshi Basupalli <vamshi@cs.wisc.edu>; v1.2; {docdatetime}

:numbered:

== Introduction

The Java CLI is a Java library and a command line interface that provides many common operation on a SWAMP instance.  These operations include getting a list of projects, packages, versions of packages, assessments, tools and platforms.  User can also create packages, upload new versions of a package, configure and start an assessment, check the status of an assessment, and download SCARF results.

== Running the CLI


=== Download the latest Java CLI

From https://github.com/mirswamp/java-cli/releases page, download the latest archive for java-cli-X.Y-jar-with-dependencies.zip archive, where X.Y stands for the latest release. Extract/Unarchive the zip file to get the jar file for the CLI. Pre-requisites for running the Java CLI is JRE-7 or above.


Run the jar file to test if it works.

Example:
```
java -jar java-cli-1.3-jar-with-dependencies.jar
```

If the above command is successfull, the output must be:
```
------------------------------------------------------------------------
Usage: <program> <command> <options>
------------------------------------------------------------------------
<command> must be one of the following:
		login
		logout
		assess
		projects
		package
		platforms
		results
		status
		tools
		user
------------------------------------------------------------------------
For information on the <options> for a <command> execute:
	<program> <command> --help or <program> <command> -h
```

Java CLI provides *commands* to perform various operations on SWAMP. A *command* is the first argument to the CLI program. Each command has its own set of options and arguments. Java CLI supports the following commands

[cols="<40%,<60%",options="header",]
|=======================================================================
|Command | Description
| login | Login into SWAMP
| logout | Logout of SWAMP
| platforms | Get the list of supported platforms
| projects |  Get the list of projects the user is part of
| tools | Get the list of tools
| package | Upload a package to SWAMP
| assess | Assess an already uploaded packages with SWAMP tools
| status | Get the status of an assessment
| results | Download SCARF results
| user | Information about the current user
|=======================================================================

To get help on each command run `java -jar java-cli-1.3-jar-with-dependencies.jar <command> --help`

=== Login in to SWAMP

`login` command must be used to login into SWAMP. The `login` command takes the following options:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--console` | Accepts username and password from the terminal
| `--filepath <CREDENTIALS_FILEPATH>` | Properties file containing
                                        *username* and *password*
| `--swamp-host <SWAMP_HOST>` | URL for SWAMP host. This is optional, default is `https://www.mir-swamp.org`
| `-help` | get help on options
|=======================================================================

The properties file should have the following as key value pairs:
```
username=<swamp-username>
password=<swamp-password>
```

If the login is successfull, the following output is displayed on the console.
```
Login successful
User UUID: <SWAMP user UUID>
```

=== SWAMP Projects Information

`projects` command must be used for the following:

1. Get the list of all the SWAMP projects the user is part of.
2. Given a project name, get the project UUID.

==== Get Project List

To get a list of all the projects that user of part of, use `--list` flag/sub-command with the `projects` command.

Example:
```
java -jar java-cli-1.3-jar-with-dependencies.jar projects --list
```

Example for the output of the above command:
```
Project Name          Project UUID                                  Project Create Date
new-project           b47380ea-a4ef-0a88-0a17-aab43d80fdbe   'Thu Jan 22 09:02:31 CST 2015'
UW SWAMP Java Software 03493356-ce76-22af-dccd-bbdb1ee169f4   'Mon Feb 03 16:52:49 CST 2014'
UW Mobile             0687979d-4b25-1036-3213-05ab438fdbbc   'Tue Jun 23 11:39:05 CDT 2015'
NICS                  afc1dea9-c375-3d30-e0c7-a885fedfa8f5   'Tue Nov 17 10:57:46 CST 2015'
MySQL Testing         0b5ae539-d0fc-7ce3-8906-900580a47ea1   'Fri Sep 19 14:04:48 CDT 2014'
MyProject             b7c3408f-bb9d-11e4-a4cd-001a4a814425   'Mon Feb 23 20:51:20 CST 2015'
4plugins              df2e7c15-4d28-4224-b25c-c2570bd91156   'Thu Jun 22 14:38:23 CDT 2017'

```

==== Get Project UUID

To get a list of all the projects that user of part of, use `--uuid` flag/sub-command with the `projects` command.

`projects` command with `--uuid` flag requires the following additional options:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--project-name <PROJECT_NAME>` | Name of the project to get the UUID for
|=======================================================================

Example:
```
java -jar java-cli-1.3-jar-with-dependencies.jar projects --uuid --project-name 4plugins
```

Example for the output of the above command:
```
df2e7c15-4d28-4224-b25c-c2570bd91156
```

=== SWAMP Platforms Information

`platform` command must be used for the following:

1. Get a list of all the platforms supported by the SWAMP instance.
2. Given a platform name, get the platform UUID.

=== Get Platforms List

To get a list of all the platforms that user of part of, use `--list` flag/sub-command with the `platforms` command.

Example:
```
java -jar java-cli-1.3-jar-with-dependencies.jar platforms --list
```

Example for the output of the above command:
```
Platform Name                  Platform UUID                         
android-ubuntu-12.04-64        8f4878ec-976f-11e4-829b-001a4a81450b  
centos-5-32                    73c7f6be-7c3a-11e6-88bc-001a4a81450b  
centos-5-64                    bf9ddb9c-7c3a-11e6-88bc-001a4a81450b  
centos-6-32                    fa5ee864-7c3a-11e6-88bc-001a4a81450b  
centos-6-64                    1c5cbe39-7c3b-11e6-88bc-001a4a81450b  
debian-7-64                    eaa6cf77-7c3b-11e6-88bc-001a4a81450b  
debian-8-64                    0cda9b68-7c3c-11e6-88bc-001a4a81450b  
fedora-18-64                   a9cfe21f-209d-11e3-9a3e-001a4a81450b  
fedora-19-64                   aebc38c3-209d-11e3-9a3e-001a4a81450b  
fedora-20-64                   89b4f7fd-7c3d-11e6-88bc-001a4a81450b  
fedora-21-64                   8efe5502-7c3d-11e6-88bc-001a4a81450b  
fedora-22-64                   9e559543-7c3d-11e6-88bc-001a4a81450b  
fedora-23-64                   a41798c7-7c3d-11e6-88bc-001a4a81450b  
fedora-24-64                   b0425ce1-7c3d-11e6-88bc-001a4a81450b  
scientific-5-64                54053a13-7c3f-11e6-88bc-001a4a81450b  
scientific-5.11-32             e7959cde-7c3e-11e6-88bc-001a4a81450b  
scientific-6-32                a72c3ab6-7c3f-11e6-88bc-001a4a81450b  
scientific-6-64                eacab258-7c3f-11e6-88bc-001a4a81450b  
ubuntu-10.04-64                f496f2ae-7c40-11e6-88bc-001a4a81450b  
ubuntu-12.04-64                18f66e9a-20aa-11e3-9a3e-001a4a81450b  
ubuntu-14.04-64                fd924363-7c40-11e6-88bc-001a4a81450b  
ubuntu-16.04-64                03b18efe-7c41-11e6-88bc-001a4a81450b  
```


==== Get Platform UUID

To get UUID of a platform, use `--uuid` flag/sub-command with the `platforms` command.

`platforms` command with `--uuid` flag requires the following additional options:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--platform-name <PLATFORM_NAME>` | Name of the platform to get the UUID for
|=======================================================================

Example:
```
java -jar java-cli-1.3-jar-with-dependencies.jar platforms -U -N ubuntu-16.04-64
```

Example for the output of the above command:
```
03b18efe-7c41-11e6-88bc-001a4a81450b
```

=== SWAMP Tools Information

`tools` command must be used for the following:

* Get a list of all the tools supported by the SWAMP
* Given a tool name, get the platform UUID

The `tools` command takes the following options:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--list` | show all the tools supported by the SWAMP instance along with their UUIDs, supported package types, and supported platforms
| `--uuid` | Flag to get UUID from tool name
| `--tool-name <TOOL_NAME>` | Name of the tool to get the UUID for
| `--project-uuid <PROJECT_UUID>` | Project UUID for extra project specific tools, this option must be used along with the `--list` option
| `--help` | get help on options
|=======================================================================

=== Packages in SWAMP

`package` command must be used for the following:

* Upload a package to SWAMP
* List supported package types
* List all the packages in a project
* Delete a set of package from a project

==== Upload a package to SWAMP

To *upload* a package, use `--upload` flag/sub-command with the `package` command.
The following additional options are required to upload a package:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--pkg-archive <PACKAGE_ARCHIVE_FILEPATH>` | Path to the archive of the package.
| `--pkg-conf <PACKAGE_CONF_FILEPATH>` | Path to package.conf file for the package.
| `--new-pkg` | Flag to specify if this should be a new package, instead of a package version. If a package with the same name already exist, it is added as a package version. This is optional.
| `--os-deps-conf <OS_DEPENDENCIES_CONF_FILEPATH>` | Path to os dependency configuration file for the package. This is optional.
| `--project-uuid <PROJECT_UUID>` | UUID of the project tht this must be associated with
|=======================================================================

Example:
```
java -jar java-cli-1.3-jar-with-dependencies.jar package -U -A ./scripts/resources/test_packages/java-cli-1.3.0/java-cli-1.1.zip -C ./scripts/resources/test_packages/java-cli-1.3.0/package.conf -P df2e7c15-4d28-4224-b25c-c2570bd91156
```
Example Output:
```
Package Version UUID: d5821bf0-5719-4e33-a49c-f31a912eaa15
```
=== Show Supported Package Types

To display the *types of software packages* supported by SWAMP, `--pkg-types` flag/sub-command must be used with the `package` command.

Example:
```
java -jar java-cli-1.3-jar-with-dependencies.jar package -T
```

Example Output:
```
Android .apk
Android Java Source Code
C/C++
Java 7 Bytecode
Java 7 Source Code
Java 8 Bytecode
Java 8 Source Code
Python2
Python3
Ruby
Ruby Padrino
Ruby Sinatra
Ruby on Rails
Web Scripting
```

==== Show User Packages

To *list* packages uploaded by a user, `--list` flag/sub-command must be used with the `package` command.

the `--list` sub-command accepts the following additional options:
[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--project-uuid <PROJECT_UUID>` | show packages that are part of this project only. If this option is not provides, all packages from all the project will be listed. This is optional
|=======================================================================

==== Delete User Packages

To *delete* a set of packages that are part of a particular project, `--delete` flag/sub-command must be used with the `package` command.

The `--delete` sub-command requires the following additional options:
[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--pkg-uuid <PKG_UUID1> <PKG_UUID2> ...` | UUIDs of packages that must be deleted
| `--project-uuid <PROJECT_UUID>` | Project UUID for the packages
|=======================================================================

 
=== Running assessments in SWAMP

`assess` command must be used for the following:

* Perform assessments in SWAMP
* List assessments
* Information about an assessment

To *perform* an assessment, provide the following options to the `assess` command:

|=======================================================================
|Option | Value
| `--run` | Flag for running assessment
| `--pkg-uuid <PKG_VERSION_UUID>` | UUID of the version of a package that must be assessed
| `--project-uuid <PROJECT_UUID>` | Project that the package is part of
| `--platform-uuid <PROJECT_UUID1> <PROJECT_UUID2> ...` | UUIDs of the platfoms that assessments must be performed on. This is optional and is only valid for `C/C++` assessments.
| `--tool-uuid <TOOL_UUID1> <TOOL_UUID2> ...` | UUIDs of the tools that must be used for assessments
|=======================================================================

=== Assessment Status

To get the status of an assessment run, `status` command must be used with the following options:

|=======================================================================
|Option | Value
| `--project-uuid <PROJECT_UUID>` | Project UUID that the assessment was part of
| `--assess-uuid <ASSESS_UUID>` | Assessment UUID
|=======================================================================

The output of the above command will display (SUCCESS|FAILURE|INPROGRESS). Incase of SUCCESS, the number of weaknesses and *results-uuid* will also be displayed on the console. 

=== Assessment Results

To get SCARF results of an assessment run, `results` command must be used with the following options:

|=======================================================================
|Option | Value
| `--project-uuid <PROJECT_UUID>` | Project UUID that the assessment was part of
| `--results-uuid <RESULTS_UUID>` | Results UUID obtained from `status` command
| `--file-path <SCARF_FILEPATH>`  | Filepath to write SCARF Results into
|=======================================================================

SCARF results from the assessment will be stored into SCARF_FILEPATH.

=== Build status on Travis CI

[![Build Status](https://travis-ci.org/mirswamp/java-cli.svg?branch=master)](https://travis-ci.org/mirswamp/java-cli)

=== Automated Test Suite

To run the automated test suite, do the following:

* Change to `java-cli` directory
* From `https://github.com/mirswamp/java-cli/releases`, download `test_packages.zip` file and unzip it in `scripts/resources` directory.
* Download *Jython-2.7.0* stand-alone jar file from http://www.jython.org/downloads.html and create a JYTHON_JAR environment variable that points to the Jar file.
* Create a `userinfo.properties` in `scripts/resources` directory. The file should have the following as key value pairs
```
username=<swamp-username>
password=<swamp-password>
project=<swamp-user-project-uuid>
hostname=<swamp-hostname> # Optional, default is mir-swamp.org
```
* run `.scripts/test.sh` script.


