= SWAMP Java CLI
:toc: left
Vamshi Basupalli <vamshi@cs.wisc.edu>; v1.3; {docdatetime}

:numbered:

== Introduction

The SWAMP Java CLI is a Java library and a command line interface that provides many common operation on a SWAMP instance.  These operations include getting a list of projects, packages, versions of packages, assessments, tools and platforms.  User can also create packages, upload new versions of a package, configure and start an assessment, check the status of an assessment, and download SCARF results.

== Installation

From https://github.com/mirswamp/java-cli/releases page, download the latest java-cli-X.Y-jar.zip archive, where X.Y stands for the latest release. Extract/Unarchive the zip file to get the jar file for the Java CLI. Pre-requisites for running the Java CLI is Java-7 or above.


To check if the `jar` file works run the following command on the terminal:
```
java -jar java-cli-1.3.jar
```

If the above command is successfull, the output will be:
```
------------------------------------------------------------------------
Usage: <program> <sub-command> <options>
------------------------------------------------------------------------
<sub-command> must be one of the following:
		login
		logout
		assess
		projects
		package
		platforms
		results
		status
		tools
		user
------------------------------------------------------------------------
For information on the <options> for a <sub-command> execute:
	<program> <command> --help or <program> <sub-command> -H
```

=== CLI with Swamp-In-The-Box (SiB) instances

SiB instances have self signed SSL/TLS certificates. Java's security model does not allow talking to an unknown server with a self-signed SSL/TLS certificates. Because of this restriction, the self-signed certificate has to be first added the trusted keystore in the local Java installation. The following are the instructions on how to do it:

1. Go to SiB from the web-browser and download the SiB self-signed certificate by following these instruction here:
https://www.thesslstore.com/blog/how-to-view-ssl-certificate-details-in-chrome-56/

2. Run the folloing commands to add the self-signed certificate to the local Java Installation's keystore:
--
a. Change the present working directory to your Java installtion directory + `jre/lib/security/`.
+
.................
   cd $JAVA_HOME/jre/lib/security
.................
+
b. Make a copy of the `cacerts` file
+
.................
   cp cacerts cacerts.original
.................
+
c. Add the certificate to the keystore (Assuming here that the self-signed certificate is stored on the desktop as www.sib-swamp.org.cer)
+
.................
   sudo keytool -importcert -alias sib-name -file ~/Desktop/www.sib-swamp.org.cer -keystore $PWD/cacerts
.................
--

3) To check if CLI works with SiB, run `login` sub-command, see section <<login>>

== Using the CLI

SWAMP Java CLI provides *sub-commands* to perform various operations on SWAMP. A *sub-command* is the first argument to the CLI program. Each sub-command has its own set of options and arguments. Java CLI supports the following sub-commands

[cols="<40%,<60%",options="header",]
|=======================================================================
|Sub-Command | Description
| login | Login into SWAMP
| logout | Logout of SWAMP
| platforms | Get the list of supported platforms
| projects |  Get the list of projects the user is part of
| tools | Get the list of tools
| package | Upload a package to SWAMP
| assess | Assess an already uploaded package with SWAMP tools
| status | Get the status of an assessment
| results | Download SCARF results
| user | Information about the current user
|=======================================================================

To get help on each sub-command run `java -jar java-cli-1.3.jar <sub-command> --help` or `java -jar java-cli-1.3.jar <sub-command> --H`.

[[login]]
=== Login

`login` sub-command is used to login into SWAMP. The `login` sub-command takes the following options:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--console` | Accepts username and password from the terminal
| `--filepath <CREDENTIALS_FILEPATH>` | Properties file containing
                                        *username* and *password*
| `--swamp-host <SWAMP_HOST>` | URL for SWAMP host. This is optional, default is `https://www.mir-swamp.org`
|=======================================================================

The properties file should have the following as key value pairs:
```
username=<swamp-username>
password=<swamp-password>
```

If the login is successfull, the following output is displayed on the console.
```
Login successful
```

Once logged in, a SWAMP sesssion is valid for *48* hours. CLI stores the session cookies in the user directory `~/.SWAMP_SESSION`

==== Application Passwords
If you have signed up with SWAMP using *github* or any other third party identiy provider then you may not have SWAMP credentials. To get username and password to login with the CLI, go to https://www.mir-swamp.org/#my-account and then to *Application Passwords* tab. Create a new password by pressing *Add New Password* button. The *username* can be seen on *My Profile* tab.

=== Logout

`logout` sub-command is used to logout of SWAMP. The `logout` sub-command does not require any options.

If the logout is successfull, the following output is displayed on the console.
```
Logout successful
```


=== Projects

`projects` sub-command is used for the following:

1. Get the list of all the SWAMP projects the user is part of.
2. Given a project name, get the project UUID.

==== Get Project List

To get a list of all the projects that user of part of, use `--list` option with the `projects` sub-command.

Example:
```
java -jar java-cli-1.3.jar projects --list
```

Example for the output of the above command:
```
UUID                                  Create Date                    Name                 
b47380ea-a4ef-0a88-0a17-aab43d80fdbe  'Thu Jan 22 09:02:31 CST 2015' new-project          
03493356-ce76-22af-dccd-bbdb1ee169f4  'Mon Feb 03 16:52:49 CST 2014' UW SWAMP Java Software
0687979d-4b25-1036-3213-05ab438fdbbc  'Tue Jun 23 11:39:05 CDT 2015' UW Mobile            
afc1dea9-c375-3d30-e0c7-a885fedfa8f5  'Tue Nov 17 10:57:46 CST 2015' NICS                 
0b5ae539-d0fc-7ce3-8906-900580a47ea1  'Fri Sep 19 14:04:48 CDT 2014' MySQL Testing        
b7c3408f-bb9d-11e4-a4cd-001a4a814425  'Mon Feb 23 20:51:20 CST 2015' MyProject            
df2e7c15-4d28-4224-b25c-c2570bd91156  'Thu Jun 22 14:38:23 CDT 2017' 4plugins             

```

==== Get Project UUID

To get a list of all the projects that user of part of, use `--uuid` option with the `projects` sub-command.

`projects` sub-command with `--uuid` option requires the following additional options:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--name <PROJECT_NAME>` | Name of the project to get the UUID for
|=======================================================================

Example:
```
java -jar java-cli-1.3.jar projects --uuid --name 4plugins
```

Example for the output of the above command:
```
df2e7c15-4d28-4224-b25c-c2570bd91156
```

=== SWAMP Platforms Information

`platform` sub-command is used for the following:

1. Get a list of all the platforms supported by the SWAMP.
2. Given a platform name, get the platform UUID.

==== Get Platforms List

To get a list of all the platforms that user of part of, use `--list` option with the `platforms` sub-command.

Example:
```
java -jar java-cli-1.3.jar platforms --list
```

Example for the output of the above command:
```
UUID                                  Name                          
8f4878ec-976f-11e4-829b-001a4a81450b  android-ubuntu-12.04-64       
fa5ee864-7c3a-11e6-88bc-001a4a81450b  centos-6-32                   
1c5cbe39-7c3b-11e6-88bc-001a4a81450b  centos-6-64                   
eaa6cf77-7c3b-11e6-88bc-001a4a81450b  debian-7-64                   
0cda9b68-7c3c-11e6-88bc-001a4a81450b  debian-8-64                   
a9cfe21f-209d-11e3-9a3e-001a4a81450b  fedora-18-64                  
aebc38c3-209d-11e3-9a3e-001a4a81450b  fedora-19-64                  
89b4f7fd-7c3d-11e6-88bc-001a4a81450b  fedora-20-64                  
8efe5502-7c3d-11e6-88bc-001a4a81450b  fedora-21-64                  
9e559543-7c3d-11e6-88bc-001a4a81450b  fedora-22-64                  
a41798c7-7c3d-11e6-88bc-001a4a81450b  fedora-23-64                  
b0425ce1-7c3d-11e6-88bc-001a4a81450b  fedora-24-64                  
a72c3ab6-7c3f-11e6-88bc-001a4a81450b  scientific-6-32               
eacab258-7c3f-11e6-88bc-001a4a81450b  scientific-6-64               
f496f2ae-7c40-11e6-88bc-001a4a81450b  ubuntu-10.04-64               
18f66e9a-20aa-11e3-9a3e-001a4a81450b  ubuntu-12.04-64               
fd924363-7c40-11e6-88bc-001a4a81450b  ubuntu-14.04-64               
03b18efe-7c41-11e6-88bc-001a4a81450b  ubuntu-16.04-64               
```

==== Get Platform UUID

To get UUID of a platform, use `--uuid` option with the `platforms` sub-command.

`platforms` sub-command with `--uuid` option requires the following additional options:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--name <PLATFORM_NAME>` | Name of the platform to get the UUID for
|=======================================================================

Example:
```
java -jar java-cli-1.3.jar platforms --uuid --name ubuntu-16.04-64
```

Example for the output of the above command:
```
03b18efe-7c41-11e6-88bc-001a4a81450b
```

=== Tools

`tools` sub-command is used for the following:

1. Get a list of all the tools supported by the SWAMP
2. Given a tool name, get the platform UUID

==== Get Tool List
To get a list of all the `tools` that SWAMP supports, use `--list` option with the `tools` sub-command. This command displays list of tools along with the tool uuid, supported package types and support platforms.

`tools` sub-command with `--list` option accepts an additional option:
[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value

| `--project-uuid <PROJECT_UUID>` | Project UUID for extra project specific tools, this option is used along with the `--list` option. This is optional
|=======================================================================

Example:
```
java -jar java-cli-1.3.jar tools --list
```

Example for the output of the above command:
```
UUID                                  Name                  Supported Package Types                  Supported Platforms
39001e1f-b741-11e6-bf70-001a4a81450b  JSHint                ["Web Scripting"]                        [scientific-6-32, ubuntu-14.04-64, ubuntu-16.04-64, android-ubuntu-12.04-64, debian-7-64, fedora-24-64, ubuntu-12.04-64, ubuntu-10.04-64, fedora-21-64, fedora-22-64, centos-6-32, fedora-18-64, fedora-19-64, centos-6-64, fedora-20-64, debian-8-64, fedora-23-64, scientific-6-64]
e7a00759-82a4-11e7-9baa-001a4a81450b  Synopsys Static Analysis (Coverity) ["C/C++"]                                [scientific-6-32, ubuntu-14.04-64, ubuntu-16.04-64, android-ubuntu-12.04-64, debian-7-64, fedora-24-64, ubuntu-12.04-64, ubuntu-10.04-64, fedora-21-64, fedora-22-64, centos-6-32, fedora-18-64, fedora-19-64, centos-6-64, fedora-20-64, debian-8-64, fedora-23-64, scientific-6-64]
44ec433d-b741-11e6-bf70-001a4a81450b  HTML Tidy             ["Web Scripting"]                        [scientific-6-32, ubuntu-14.04-64, ubuntu-16.04-64, android-ubuntu-12.04-64, debian-7-64, fedora-24-64, ubuntu-12.04-64, ubuntu-10.04-64, fedora-21-64, fedora-22-64, centos-6-32, fedora-18-64, fedora-19-64, centos-6-64, fedora-20-64, debian-8-64, fedora-23-64, scientific-6-64]
4bb2644d-6440-11e4-a282-001a4a81450b  Parasoft C/C++test    ["C/C++"]                                [scientific-6-32, ubuntu-14.04-64, ubuntu-16.04-64, debian-7-64, fedora-24-64, ubuntu-12.04-64, ubuntu-10.04-64, fedora-21-64, fedora-22-64, centos-6-32, fedora-18-64, fedora-19-64, centos-6-64, fedora-20-64, debian-8-64, fedora-23-64, scientific-6-64]
```

==== Get Tool UUID

To get a tool's UUID, use `--uuid` option with the `tools` sub-command.
`tools` sub-command with `--uuid` option requires the following additional option:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--name <TOOL_NAME>` | Name of the tool to get the UUID for
|=======================================================================

Example:
```
java -jar java-cli-1.3.jar tools --uuid --name PMD
```

Example for the output of the above command:
```
163f2b01-156e-11e3-a239-001a4a81450b
```

=== Packages in SWAMP

`package` sub-command is used for the following:

1. Upload a package to SWAMP
2. List supported package types
3. List all the packages in a project
4. Delete packages from a project

==== Upload a package to SWAMP

To *upload* a package, use `--upload` option with the `package` sub-command.
The following additional options are required to upload a package:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--pkg-archive <PACKAGE_ARCHIVE_FILEPATH>` | Path to the archive of the package.
| `--pkg-conf <PACKAGE_CONF_FILEPATH>` | Path to https://github.com/mirswamp/java-cli/blob/master/package.conf.adoc[package.conf] file for the package.
| `--new` | Flag/Option to specify if this should be a new package instead of a package version. If a package with the same name already exist, CLI adds this package as a package version. `--new` flag overrides it and stores it as a new package. This is optional.
| `--os-deps '<platform=dependency1 dependency2 ...>'` | OS package dependencies specified as `key=value` format. Use this option multiple times to specify dependency for multiple SWAMP platforms. This is optional.
| `--project-uuid <PROJECT_UUID>` | UUID of the project that this package is associated with
|=======================================================================

Example:
```
java -jar java-cli-1.3.jar package --upload --pkg-archive /Users/vamshi/swamp/api-dev/java-cli/scripts/resources/test_packages/railsgoat-9052b4fcf0/railsgoat-9052b4fcf0.zip -pkg-conf /Users/vamshi/swamp/api-dev/java-cli/scripts/resources/test_packages/railsgoat-9052b4fcf0/package.conf --os-deps 'ubuntu-16.04-64=libsqlite3-dev libmysqlclient-dev' --os-deps 'debian-7-64=libsqlite3-dev libmysqlclient-dev' --project-uuid df2e7c15-4d28-4224-b25c-c2570bd91156 --new
```

If the above command is successfull, the output will be:
```
Package Version UUID: d5821bf0-5719-4e33-a49c-f31a912eaa15
```
==== Show Supported Package Types

To display the *types of software packages* supported by SWAMP, `--pkg-types` option is used with the `package` sub-command.

Example:
```
java -jar java-cli-1.3.jar package -pkg-types
```

Output from the above command:
```
Android .apk
Android Java Source Code
C/C++
Java 7 Bytecode
Java 7 Source Code
Java 8 Bytecode
Java 8 Source Code
Python2
Python3
Ruby
Ruby Padrino
Ruby Sinatra
Ruby on Rails
Web Scripting
```

==== Show User Packages

To *list* packages uploaded by a user, `--list` option is used with the `package` sub-command.

The package sub-command with the `--list` option accepts the following additional options:
[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--project-uuid <PROJECT_UUID>` | show packages that are part of this project only. If this option is not provides, all packages from all the project will be listed. This is optional
|=======================================================================

==== Delete User Packages

To *delete* a set of packages that are part of a particular project, `--delete` option is used with the `package` sub-command.

`package` sub-command with `--delete` sub-command requires the following additional options:
[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--pkg-uuid <PKG_UUID1> <PKG_UUID2> ...` | UUIDs of packages that must be deleted
| `--project-uuid <PROJECT_UUID>` | Project UUID for the packages
|=======================================================================

 
=== Assessments in SWAMP

`assess` sub-command is used for the following:

* Perform assessments in SWAMP
* List assessments


==== Perform assessments in SWAMP

To *perform* an assessment, `--run` option is used with `assess` sub-command. 

`assess` sub-command with the `--run` option requires the following additional options:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--pkg-uuid <PKG_VERSION_UUID>` | UUID of the version of a package that must be assessed
| `--project-uuid <PROJECT_UUID>` | Project that the package is part of
| `--platform-uuid <PLATFORM_UUID1 PLATFORM_UUID2> ...` | UUIDs of the platfoms that assessments must be performed on. This is optional and is only valid for `C/C++` assessments.
| `--tool-uuid <TOOL_UUID1> <TOOL_UUID2> ...` | UUIDs of the tools that must be used for assessments
|=======================================================================

Example:
```
java -jar java-cli-1.3.jar assess --run --pkg-uuid 74029aa1-f6e4-41cc-b1a0-df2116be2cbe --project-uuid df2e7c15-4d28-4224-b25c-c2570bd91156 --tool-uuid 56872C2E-1D78-4DB0-B976-83ACF5424C52 163f2b01-156e-11e3-a239-001a4a81450b
```

Example output of the above command:
```
Assessment UUIDs: [1f353b01-6b81-4a7c-84f8-02e2131a7373, 96e6e4e0-efce-4216-bff9-b20b30ca2e83]
```

==== List Assessments

To *list* packages uploaded by a user, `--list` option along with `--name <project_name>` must be used with the `assess` sub-command.



=== Assessment Status

To get the status of an assessment run, `status` sub-command is used with the following options:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--project-uuid <PROJECT_UUID>` | Project UUID that the assessment was part of
| `--assess-uuid <ASSESS_UUID>` | Assessment UUID
|=======================================================================

The output of the above sub-command will display (SUCCESS|FAILURE|INPROGRESS). Incase of SUCCESS, the number of weaknesses and *results-uuid* will also be displayed on the console. 


Example:

```
java -jar java-cli-1.3.jar status --assess-uuid 96e6e4e0-efce-4216-bff9-b20b30ca2e83 --project-uuid df2e7c15-4d28-4224-b25c-c2570bd91156
```

Example output of the above command:
```
SUCCESS, 33, f4856ee8-b402-11e7-92c3-001a4a814413
```

=== Assessment Results

To get SCARF results of an assessment run, `results` sub-command is used with the following options:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Option | Value
| `--project-uuid <PROJECT_UUID>` | Project UUID that the assessment was part of
| `--results-uuid <RESULTS_UUID>` | Results UUID obtained from `status` sub-command
| `--file-path <SCARF_FILEPATH>`  | Filepath to write SCARF Results into
|=======================================================================

SCARF results from the assessment will be stored into SCARF_FILEPATH.


Example:
```
java -jar java-cli-1.3.jar results --results-uuid f4856ee8-b402-11e7-92c3-001a4a814413 --project-uuid df2e7c15-4d28-4224-b25c-c2570bd91156 --file-path $PWD/scarf-results.xml
```
=== Exit Codes
In case of errrors or exceptions the Java CLI program returns the following exit codes:

[cols="<40%,<60%",options="header",]
|=======================================================================
|Exit Code | Description
| 0 | Everything is fine or No errors
| 1 | Incorrect command line options
| 2 | Command line parser error
| 3 | Invalid UUID of a Tool, Project, Package, Assessment
| 4 | Incompatible tuple, example: Using Java tool on a C/C++ package
| 5 | User session expired
| 6 | User session restore error
| 7 | User session save error
| 8 | No default platform
| 20+ | HTTP exception
|=======================================================================

== Building from Sources

Clone https://github.com/mirswamp/java-api.git, and run the following command to build `java-api`:
```
mvn install -DskipTests
```

Clone https://github.com/mirswamp/java-cli.git, and run the following command to build `java-cli`:
```
mvn package -DskipTests
```

Run `java-cli-1.X.X-jar-with-dependencies.jar` inside `target` directory.

Example:
```
java -jar ./target/java-cli-1.3.3-jar-with-dependencies.jar
```


== Automated Test Suite

To run the automated test suite, do the following:

* Change to `java-cli` directory
* From `https://github.com/mirswamp/java-cli/releases`, download `test_packages.zip` file and unzip it in `scripts/resources` directory.
* Download *Jython-2.7.0* stand-alone jar file from http://www.jython.org/downloads.html and create a JYTHON_JAR environment variable that points to the Jar file.
* Create a `userinfo.properties` in `scripts/resources` directory. The file should have the following as key value pairs
```
username=<swamp-username>
password=<swamp-password>
project=<swamp-user-project-uuid>
hostname=<swamp-hostname> # Optional, default is mir-swamp.org
```
* run `.scripts/test.sh` script.


